services:
  pg:
    image: postgres:18-alpine
    env_file:
      - .env
    networks:
      - webapps

  redis:
    image: redis:8.6.1-trixie
    networks:
      - webapps

  backend:
    container_name: backend-adit
    image: ghcr.io/adityabastyas/koda-b6-backend-cicd:latest
    env_file:
      - .env
    ports:
      - 20500:8888
    networks:
      - webapps
      - network_adit
    depends_on:
      - pg
      - redis

  frontend:
    container_name: web-adit
    image: nginx:alpine
    ports:
      - 20501:80
    networks:
      - network_adit

networks:
  pman_web:
    external: true
  webapps: