POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "1234"
}

###

POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
  "email": "halo@mail.com",
  "password": "1111"
}

###

GET /users HTTP/1.1
Host: localhost:8888

###

PATCH /users/0 HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
  "email": "updated@mail.com",
  "password": "9999"
}

###

DELETE /users/0 HTTP/1.1
Host: localhost:8888


### 
POST /register HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
  "email": "adit@mail.com",
  "password": "1234"
}

### 
POST /login HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "1234"
}

### 
POST /login HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "9999"
}

###

POST  /products HTTP/1.1
Host: localhost:8888
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzYxNjA0MDMsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjR9.LR35O7f7-XxZFlBVKn020L8ekbnI-vkvxeSC-pNXY7Y
Content-Type: application/json

{
  "name": "Coffee Latte",
  "price": 20000,
  "kategory_id": 2
}

###
GET /products HTTP/1.1
Host: localhost:8888

###
GET /products/1 HTTP/1.1
Host: localhost:8888

###



GET /product-variant/1 HTTP/1.1
Host: localhost:8888

###

GET /product-sizes/2 HTTP/1.1
Host: localhost:8888

###
GET http://localhost:8888/reviews
###

POST /auth/register HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "full_name": "Admin",
    "email": "admin@mail.com",
    "password": "123456"
}

###
POST /auth/login HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "123456"
}


###

POST /auth/forgot-password HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "h@mail.com"
   
}

###

PATCH http://localhost:8888/auth/forgot-password?email=h@mail.com
Content-Type: application/json

{
  "code": "828615",
  "new_password": "1234567"
}