definitions:
  models.ForgotPasswordInput:
    properties:
      email:
        type: string
    type: object
  models.PromoInput:
    properties:
      description:
        type: string
      discount_value:
        type: integer
      promo_type:
        type: string
      title:
        type: string
    type: object
  models.ResetPasswordInput:
    properties:
      code:
        type: string
      new_password:
        type: string
    type: object
  models.Response:
    properties:
      message:
        type: string
      result: {}
      success:
        type: boolean
    type: object
  models.UserLoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.UserRegisterInput:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/forgot-password:
    patch:
      consumes:
      - application/json
      parameters:
      - description: Email
        in: query
        name: email
        required: true
        type: string
      - description: Reset Password Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.ResetPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Reset password dengan code OTP
      tags:
      - auth
    post:
      consumes:
      - application/json
      parameters:
      - description: Email input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.ForgotPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Request forgot password
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Login Input
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Login user
      tags:
      - auth
  /promos:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Ambil semua promo
      tags:
      - promo
    post:
      consumes:
      - application/json
      parameters:
      - description: Promo Input
        in: body
        name: promo
        required: true
        schema:
          $ref: '#/definitions/models.PromoInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: Tambah promo baru
      tags:
      - promo
  /promos/{id}:
    delete:
      parameters:
      - description: Promo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: Hapus promo
      tags:
      - promo
    get:
      parameters:
      - description: Promo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Ambil 1 promo berdasarkan ID
      tags:
      - promo
    patch:
      consumes:
      - application/json
      parameters:
      - description: Promo ID
        in: path
        name: id
        required: true
        type: integer
      - description: Promo Input
        in: body
        name: promo
        required: true
        schema:
          $ref: '#/definitions/models.PromoInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: Edit promo
      tags:
      - promo
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Register Input
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserRegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Register user baru
      tags:
      - auth
swagger: "2.0"
